### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by martinoywa** [martinoywa/creative-gan#16]
The project doesn't have any tests. Some ideas could be:

- [x]  Checkpoints/weights exist

- [x]  Templates being loaded

- [x] Static files being loaded

- [x] Images being generated

Feel free to add or remove any.

**Comment by KamauNdichu** [comment]
will check it mate

**Comment by martinoywa** [comment]
Cool

**Comment by martinoywa** [comment]
Have you been able to work on some tests?

**Comment by cesarWrites** [comment]
I have identified two test cases though I haven't updated them yet.
1.The model successfully generates new images.
2. The download button generates images.
When I work on the changes in my side ,
Should I just git push or I have to git pull first ?

**Comment by martinoywa** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}

**Comment by KamauNdichu** [comment]
hey. am almost done. am testing the functionality of the download button
using a web api coz I dont have the actual project api. but that's for
testing we'll integrate it later. I'll try my best to be through by monday
so that I can share the code.
😊

**Comment by martinoywa** [comment]
Cool, we're waiting for the new update

**Comment by KamauNdichu** [comment]
cool
